namespace Prismatoid.NativeInterop
{
    public enum PrismError
    {
        PRISM_OK = 0,
        PRISM_ERROR_NOT_INITIALIZED,
        PRISM_ERROR_INVALID_PARAM,
        PRISM_ERROR_NOT_IMPLEMENTED,
        PRISM_ERROR_NO_VOICES,
        PRISM_ERROR_VOICE_NOT_FOUND,
        PRISM_ERROR_SPEAK_FAILURE,
        PRISM_ERROR_MEMORY_FAILURE,
        PRISM_ERROR_RANGE_OUT_OF_BOUNDS,
        PRISM_ERROR_INTERNAL,
        PRISM_ERROR_NOT_SPEAKING,
        PRISM_ERROR_NOT_PAUSED,
        PRISM_ERROR_ALREADY_PAUSED,
        PRISM_ERROR_INVALID_UTF8,
        PRISM_ERROR_INVALID_OPERATION,
        PRISM_ERROR_ALREADY_INITIALIZED,
        PRISM_ERROR_BACKEND_NOT_AVAILABLE,
        PRISM_ERROR_UNKNOWN,
        PRISM_ERROR_INVALID_AUDIO_FORMAT,
        PRISM_ERROR_INTERNAL_BACKEND_LIMIT_EXCEEDED,
        PRISM_ERROR_BACKEND_ENTERED_UNDEFINED_STATE,
        PRISM_ERROR_LIBRARY_LOAD_FAILED,
        PRISM_ERROR_LIBRARY_INVALID,
        PRISM_ERROR_INCOMPATIBLE_ABI,
        PRISM_ERROR_COUNT,
    }
}
